#!/usr/bin/env bash

# River's config file is a bash script. River runs ~/.config/river/init when you log in.

riverctl spawn "dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"

riverctl spawn "fcitx5"
riverctl spawn "quickshell"
riverctl spawn "mako"
riverctl spawn "gammastep -O 3800"
riverctl spawn "handy --start-hidden"

riverctl set-repeat 45 200
riverctl input "pointer-1-1-kanata" tap enabled
riverctl input "pointer-1-1-kanata" drag enabled
riverctl input "pointer-1-1-kanata" drag-lock enabled
riverctl input "pointer-1-1-kanata" disable-while-typing disabled
riverctl input "pointer-1-1-kanata" disable-while-trackpointing disabled

riverctl border-width 0
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 -main-ratio 0.5 &
riverctl focus-follows-cursor always
riverctl set-cursor-warp on-focus-change

# i3 like shorcuts

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
done
riverctl map normal Super+Shift q close
riverctl map normal Super+Shift e exit
riverctl spawn-tagmask 00000000000000000000000111111111

# Misc shortcuts

riverctl map normal Super p spawn "fuzzel &" # App launcher
riverctl map normal Mod1 c spawn "grim - | wl-copy" # Screenshot clipboard
riverctl map normal Mod1 a spawn "$HOME/.config/nixos/scripts_as_dotfiles/mako/dismiss_oldest_notification.sh"
riverctl map normal Mod1 z spawn "makoctl mode -t hidden"
riverctl map normal Mod1 space spawn "handy --toggle-transcription"

# Initial apps (Equivalent of workspaces 1,2,3 in i3/Sway)

riverctl rule-add -app-id tmux.term tags 1
# DIR=$(zoxide query ~/projects/)
# SESSION=${DIR##*/}
riverctl spawn "ghostty --class=tmux.term --gtk-tabs-location=hidden --initial-command='cd ~/.config/nixos && tmux new-session -A -s nixos'"
riverctl rule-add -app-id firefox tags 2
riverctl spawn "firefox"
riverctl rule-add -app-id notes.term tags 4
riverctl spawn "ghostty --class=notes.term --gtk-tabs-location=hidden --initial-command='cd $HOME/notes/ && hx Systems.md'" 
riverctl set-focused-tags 1

# Scratchpads

LARGE_W=1870
LARGE_H=1150

riverctl rule-add -app-id wifi.term tags 512 # 00000000000000000000001000000000
riverctl rule-add -app-id wifi.term float
riverctl rule-add -app-id wifi.term dimensions 700 700
riverctl spawn "ghostty --class=wifi.term --gtk-tabs-location=hidden --initial-command='nmtui-connect; exec bash'"
riverctl map normal Super q spawn 'sh -c "riverctl toggle-focused-tags 512; riverctl focus-view next"'

riverctl rule-add -app-id audio.term tags 1024 # 00000000000000000000010000000000
riverctl rule-add -app-id audio.term float
riverctl rule-add -app-id audio.term dimensions 700 500
riverctl spawn "ghostty --class=audio.term --gtk-tabs-location=hidden --initial-command='pulsemixer; exec bash'"
riverctl map normal Super w spawn 'sh -c "riverctl toggle-focused-tags 1024; riverctl focus-view next"'

riverctl rule-add -app-id brightness.term tags 2048 # 00000000000000000000100000000000
riverctl rule-add -app-id brightness.term float
riverctl rule-add -app-id brightness.term dimensions 700 200
riverctl spawn "ghostty --class=brightness.term --gtk-tabs-location=hidden --initial-command='$HOME/.config/nixos/scripts/brightnessctl.sh; exec bash'"
riverctl map normal Super e spawn 'sh -c "riverctl toggle-focused-tags 2048; riverctl focus-view next"'

riverctl rule-add -app-id aichat.term tags 4096 # 00000000000000000001000000000000
riverctl rule-add -app-id aichat.term float
riverctl rule-add -app-id aichat.term dimensions "$LARGE_W" "$LARGE_H"
riverctl spawn "alacritty --class 'aichat.term' -e bash -c 'export OPENROUTER_API_KEY=\$(cat /run/secrets/OPENROUTER_API_KEY); aichat; exec bash'"
riverctl map normal Mod1 h spawn 'sh -c "riverctl toggle-focused-tags 4096; riverctl focus-view next"'

riverctl rule-add -app-id aieditor.term tags 8192 # 00000000000000000010000000000000
riverctl rule-add -app-id aieditor.term float
riverctl rule-add -app-id aieditor.term dimensions "$LARGE_W" "$LARGE_H"
riverctl spawn "alacritty --class 'aieditor.term'"
riverctl map normal Mod1 u spawn 'sh -c "riverctl toggle-focused-tags 8192; riverctl focus-view next"'

riverctl rule-add -app-id aieditor2.term tags 16384 # 00000000000000000100000000000000
riverctl rule-add -app-id aieditor2.term float
riverctl rule-add -app-id aieditor2.term dimensions "$LARGE_W" "$LARGE_H"
riverctl spawn "alacritty --class 'aieditor2.term'"
riverctl map normal Mod1 i spawn 'sh -c "riverctl toggle-focused-tags 16384; riverctl focus-view next"'

riverctl rule-add -app-id news.term tags 32768 # 00000000000000001000000000000000
riverctl rule-add -app-id news.term float
riverctl rule-add -app-id news.term dimensions "$LARGE_W" "$LARGE_H"
riverctl spawn "ghostty --class='news.term' --title='news' --gtk-tabs-location=hidden --window-decoration=auto --initial-command='newsraft'"
riverctl map normal Mod1 d spawn 'sh -c "riverctl toggle-focused-tags 32768; riverctl focus-view next"'

riverctl rule-add -app-id ghdash.term tags 65536 # 00000000000000010000000000000000
riverctl rule-add -app-id ghdash.term float
riverctl rule-add -app-id ghdash.term dimensions "$LARGE_W" "$LARGE_H"
riverctl spawn "ghostty --class='ghdash.term' --title='ghdash' --gtk-tabs-location=hidden --window-decoration=auto --initial-command='gh-dash; exec bash'"
riverctl map normal Mod1 s spawn 'sh -c "riverctl toggle-focused-tags 65536; riverctl focus-view next"'

# Toggeable widgets

riverctl spawn "$HOME/.config/nixos/scripts/quickshell__keybindhelper.qml"
riverctl map normal Super h spawn "sh -c 'qs ipc -p $HOME/.config/nixos/scripts/quickshell__keybindhelper.qml call KeybindHelperHandler toggle'"

