theme = "nightfox"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left =  [] 
center = ["read-only-indicator", "file-modification-indicator", "file-name", "total-line-numbers"]
right = [ "diagnostics", "register", "file-encoding", "spinner"]

[editor]
jump-label-alphabet = "asdfghjklqwertyuiopzxcvbnm"
true-color = true

[editor.file-picker]
hidden = false
git-ignore = false

[editor.soft-wrap]
enable = true

[keys.normal]
C-r = [
    ":write-all",
    ":insert-output scooter --no-stdin >/dev/tty",
    ":redraw",
    ":reload-all"
]
# use system clipboard
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_to_clipboard"
Y = "yank_joined_to_clipboard"
R = "replace_selections_with_clipboard"
d = ["yank_to_clipboard", "delete_selection_noyank"]
