set -g mouse on
set -g set-clipboard on
set -g allow-passthrough on
set -g detach-on-destroy off
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -ga terminal-overrides ",*256col*:Tc"
set-option -as terminal-overrides "xterm-256color:Ms=\\E]52;c%p1%.0s;%p2%s\\7" # only for mosh - https://github.com/mobile-shell/mosh/pull/1054
set -g default-terminal "tmux-256color"
set-option -g default-shell /run/current-system/sw/bin/bash
set-option -g default-command /run/current-system/sw/bin/fish
set -g history-limit 100000
set -g mode-keys vi
set -g escape-time 0

# Shortcuts

## Base

bind -n M-t run-shell "tmux neww -b"
bind -n M-w kill-pane
bind -n M-k run-shell "$HOME/.config/nixos/scripts_as_dotfiles/tmux/focus_right.sh"
bind -n M-j run-shell "$HOME/.config/nixos/scripts_as_dotfiles/tmux/focus_left.sh"
bind -n M-n split-window -h -p 37 -c "#{pane_current_path}"
bind -n M-m split-window -v -c "#{pane_current_path}"
bind -n M-y split-window -h -p 37 -c "#{pane_current_path}" yazi
bind -n M-r command-prompt -I "#W" "rename-window '%%'"

## Copy mode

bind -n M-f copy-mode
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi M-v send-keys -X rectangle-toggle
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel

## Lazygit in the current directory

bind -n M-g run-shell "$HOME/.config/nixos/scripts_as_dotfiles/tmux/toggle_lazygit.sh"

## Session manager

bind -n M-o run-shell "$HOME/.config/nixos/scripts_as_dotfiles/tmux/sessionizer.sh"
# bind -n M-Tab switch-client -l
bind -n M-Tab run-shell "sesh last"

## Git scripts

bind -n M-p run-shell "tmux neww ~/.config/nixos/scripts_as_dotfiles/tmux/command_palette.sh"

## Claude-code fix for pasting images

bind -n M-v run-shell "$HOME/.config/nixos/scripts_as_dotfiles/claudecode/wlpaste__img2path.sh | tmux load-buffer - ; tmux paste-buffer"

# Panel border highlights

set -g pane-active-border-style    "fg=colour46"
set -g pane-border-style           "fg=colour236"

# Status bar style (different from local)

set -g window-status-format "   #W"
set -g window-status-current-format "   #W"
set -g status-position top
set -g status-left ""
set -g status-justify right
set -g status-right                "              #[bg=#222828,fg=colour201] #S   "
set -g status-style                "bg=#222828"
set -g window-status-style         "bg=#222828,fg=colour248"
set -g window-status-current-style "bg=#222828,fg=colour46"
set -g message-command-style       "bg=colour46,fg=#222828, bold"
set -g message-style               "bg=colour46,fg=#222828, bold"

# Use C-a prefix to distinguish from local C-b
set -g prefix C-a
unbind C-b
bind C-a send-prefix
